import "./globals.css";
import { Raleway, Open_Sans } from "next/font/google";
import { CustomLayout } from "./components";
import i18nConfig from "@/i18nConfig";
import { dir } from "i18next";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout(props) {
  return (
    <html
      lang={props.params.locale}
      dir={dir(props.params.locale)}
      className={`${raleway.variable} ${openSans.variable} sans-serif`}
    >
      <body>
        <CustomLayout {...props} />
      </body>
    </html>
  );
}
